### ISSUE TITLE
[Feature Request] Short key for rotating instances

### ISSUE THREAD

**Issue by ChrisHoyer** [SimonGit0/circuit-drawing#2]
It would be helpful if there were a shortcut key for rotating instances and objects. 
So far, only mirroring with the `X` and `Y` keys has been implemented.

My suggestion would be `SHIFT + R`

**Comment by SimonGit0** [comment]
Added STRG+R and STRG+SHIFT+R as shortcutkey for rotation. (Clockwise / counter clockwise)
